/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test/test_cache_util.check" instead.
 */

#include <check.h>

#line 1 "test/test_cache_util.check"
#include <stdlib.h>
#include "cache.h"
#include "cache_util.h"

START_TEST(util_test1)
{
#line 6
	cli_arg arg;
	arg.counter = 0;
	arg.vector = malloc(10 * sizeof(char*) );
	char line[BUFFER_LENGTH] = "This is a test";
	ck_assert_int_eq(parse_cli(line, &arg), SUCCESS);
	for(int i = 0; i<arg.counter; i++)
		free(arg.vector[i]);
	free(arg.vector);

}
END_TEST

START_TEST(util_test2)
{
#line 16
	cli_arg arg;
	arg.counter = 0;
	arg.vector = malloc(10 * sizeof(char*) );
	char line[BUFFER_LENGTH] = "This is a test";
	parse_cli(line, &arg);
	ck_assert_str_eq(arg.vector[1], "is");
	for(int i = 0; i<arg.counter; i++)
		free(arg.vector[i]);
	free(arg.vector);

}
END_TEST

START_TEST(util_test3)
{
#line 27
	cli_arg arg;
	arg.counter = 0;
	arg.vector = malloc(10 * sizeof(char*) );
	char line[BUFFER_LENGTH] = "This is a test";
	parse_cli(line, &arg);
	ck_assert_int_eq(arg.counter, 4);
	for(int i = 0; i<arg.counter; i++)
		free(arg.vector[i]);
	free(arg.vector);


}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, util_test1);
    tcase_add_test(tc1_1, util_test2);
    tcase_add_test(tc1_1, util_test3);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
